### ISSUE TITLE
ModuleNotFoundError: No module named 'anime_dl'

### ISSUE THREAD

**Issue by leptoid** [Xonshiz/anime-dl#104]
Hi.  Another issue I found but did not understand completely yet... 

```
python3 ./Anime_dl.py 
Traceback (most recent call last):
  File "./Anime_dl.py", line 8, in <module>
    import sites
  File "/media/1TB/Downloads/Torrents/anime-dl/anime-dl/anime-dl-master/anime_dl/sites/__init__.py", line 1, in <module>
    from . import crunchyroll
  File "/media/1TB/Downloads/Torrents/anime-dl/anime-dl/anime-dl-master/anime_dl/sites/crunchyroll.py", line 6, in <module>
    import anime_dl
ModuleNotFoundError: No module named 'anime_dl'

```
To be precise, I understand, but I don't know where it stems from... I think it happens when the Crunchyroll stuff is called, but there isn't exactly anything i can fill in that spot. ;)

**Comment by leptoid** [comment]
Ok... now I understand it.  I don't know how to correct it yet but I'm working on it.  This error comes from the inability to import a parent directory.  Since anime_dl is the parent directory to all script functions, it is not being referenced/imported.  I didn't think it should, but it appears to be happening in Python2.7, Python 3, and Python 3.7.  More to come as I learn more.

**Comment by tantalizingbana** [comment]
@leptoid i am getting issues with no module named anime_dl.common when running via python.

**Comment by leptoid** [comment]
The is because it doesn't know how to find the anime_dl folder.  I would assume that if all references to "anime_dl." were removed, things would be okie dokie again.  Technically, using an old but 'correct' (Newer than 2.7.* older than 3.5.*) version of Python should work too.  I'm still figuring it out.

**Comment by leptoid** [comment]
Ok... I figured it out.  I will wait for @Xonshiz to verify/approve as he is way better at this than me.
