### ISSUE TITLE
Error downloading Boruto (local variable 'rtmpDL' referenced before assignment)

### ISSUE THREAD

**Issue by spoilalot** [Xonshiz/anime-dl#11]
anime-dl.exe -i "http://www.crunchyroll.com/boruto-naruto-next-generations/episode-3-metal-lee-goes-wild-732527" -u "" -p "" -r "1080p"
Trying to login...
Logged in successfully...
Grabbing Links for 1080p Streams.
Writing subtitles to files...
Writing subtitles to files...
Writing subtitles to files...
Writing subtitles to files...
Writing subtitles to files...
Writing subtitles to files...
Traceback (most recent call last):
  File "anime_dl\__main__.py", line 18, in <module>
  File "anime_dl\__main__.py", line 69, in main
  File "anime_dl\AnimeDL.py", line 27, in __init__
  File "anime_dl\sites\crunchyroll.py", line 42, in __init__
  File "anime_dl\sites\crunchyroll.py", line 215, in singleEpisode
**UnboundLocalError: local variable 'rtmpDL' referenced before assignment**
Failed to execute script __main__

**Comment by Xonshiz** [comment]
Fixed.
