### ISSUE TITLE
cant seem to login and dont know why

### ISSUE THREAD

**Issue by drached** [Xonshiz/anime-dl#115]
I am trying to download Dr.Stone but i cant seem to get the script working
https://pastebin.com/Z43hSmGZ

**Comment by saieeshb** [comment]
Same with me here. I just get a `Failed to login!!` error.

**Comment by besweeet** [comment]
Same. Mine says:

Trying to login...
Failed Login!!!
Traceback (most recent call last):
  File "anime_dl\__main__.py", line 16, in <module>
  File "anime_dl\__main__.py", line 73, in Main
  File "anime_dl\Anime_dl.py", line 30, in __init__
  File "anime_dl\sites\crunchyroll.py", line 49, in __init__
NameError: global name 'exit' is not defined
[4004] Failed to execute script __main__

Using youtube-dl in the meantime.

**Comment by Pfuenzle** [comment]
I also get 
'''
Trying to login...
Failed Login!!!
'''
When trying to login on Crunchyroll.
I tried with both username and email, nothing is working

**Comment by Xonshiz** [comment]
Any new comers, please read this : #120
