### ISSUE TITLE
ModuleNotFoundError: No module named 'compat'

### ISSUE THREAD

**Issue by Haejien** [Xonshiz/anime-dl#2]
Next import error:
```
  File "AnimeDL.py", line 9, in <module>
    import sites
  File "C:\Users\x\Desktop\anime-dl-master\anime_dl\sites\__init__.py", line 1, in <module>
    import sites.crunchyroll
  File "C:\Users\x\Desktop\anime-dl-master\anime_dl\sites\crunchyroll.py", line 10, in <module>
    from external.utils import bytes_to_intlist, intlist_to_bytes
  File "C:\Users\x\Desktop\anime-dl-master\anime_dl\external\__init__.py", line 1, in <module>
    import external.aes
  File "C:\Users\x\Desktop\anime-dl-master\anime_dl\external\aes.py", line 5, in <module>
    from .utils import bytes_to_intlist, intlist_to_bytes
  File "C:\Users\x\Desktop\anime-dl-master\anime_dl\external\utils.py", line 37, in <module>
    from compat import (
ModuleNotFoundError: No module named 'compat'
```

**Comment by Xonshiz** [comment]
working on my end. Just downloaded bunch of videos. Let me know if Py script still causes some funky errors. After that I'll push the windows binary. PyCharm doesn't show these errors. Gawd dammit PythonPath :/

**Comment by Haejien** [comment]
New one now haha:

```
Traceback (most recent call last):
  File "AnimeDL.py", line 9, in <module>
    import sites
  File "C:\Users\Administrator\Desktop\anime-dl-master\anime_dl\sites\__init__.py", line 1, in <module>
    import sites.crunchyroll
  File "C:\Users\Administrator\Desktop\anime-dl-master\anime_dl\sites\crunchyroll.py", line 10, in <module>
    from external.utils import bytes_to_intlist, intlist_to_bytes
  File "C:\Users\Administrator\Desktop\anime-dl-master\anime_dl\external\__init__.py", line 1, in <module>
    import external.aes
  File "C:\Users\Administrator\Desktop\anime-dl-master\anime_dl\external\aes.py", line 5, in <module>
    from utils import bytes_to_intlist, intlist_to_bytes
ModuleNotFoundError: No module named 'utils'
```

**Comment by Xonshiz** [comment]
Just pushed an update from desktop. It closed automatically. Re-opening, please try again and let me know. Should work now. Please make sure you're running on Python 3

**Comment by Haejien** [comment]
Still get the same error after the update:
```

C:\Users\Administrator\Desktop\anime-dl-master\anime_dl>python --version
Python 3.6.0
```

**Comment by Xonshiz** [comment]
Okay, please check again. PyCharm uses PYTHONPATH and the imports work just fine inside it. Outside it, THIS happens. (Learned something new). Check again and let me know...

**Comment by Haejien** [comment]
Fixed utils back to compat however:

```
Traceback (most recent call last):
  File "AnimeDL.py", line 9, in <module>
    import sites
  File "C:\Users\Administrator\Desktop\anime-dl-master\anime_dl\sites\__init__.py", line 1, in <module>
    import sites.crunchyroll
  File "C:\Users\Administrator\Desktop\anime-dl-master\anime_dl\sites\crunchyroll.py", line 10, in <module>
    from external.utils import bytes_to_intlist, intlist_to_bytes
  File "C:\Users\Administrator\Desktop\anime-dl-master\anime_dl\external\__init__.py", line 1, in <module>
    import external.aes
  File "C:\Users\Administrator\Desktop\anime-dl-master\anime_dl\external\aes.py", line 5, in <module>
    from external.utils import bytes_to_intlist, intlist_to_bytes
  File "C:\Users\Administrator\Desktop\anime-dl-master\anime_dl\external\utils.py", line 37, in <module>
    from compat import (
ModuleNotFoundError: No module named 'compat'
```

**Comment by Xonshiz** [comment]
son of a ... -_-
Please bear with this shit, because it's working on my end just fine. :/

**Comment by Haejien** [comment]
Oh yeah I understand, glad you're active and willing to work through these problems.

**Comment by Xonshiz** [comment]
Check this update and let me know if its working or not...

**Comment by Haejien** [comment]
No more errors but running --help/-h and I get no output, assume that's just because running it on windows.

**Comment by Xonshiz** [comment]
Try downloading an episode. Don't forget to put ffmpeg in the directory of this script, or in the system path.

**Comment by Haejien** [comment]
No good:

```
C:\Users\Administrator\Desktop\anime-dl-master\anime_dl>python AnimeDL.py -i http://www.crunchyroll.com/kemono-friends/episode-8-ppp-live-728273 -u username -p password

C:\Users\Administrator\Desktop\anime-dl-master\anime_dl>
```

**Comment by Xonshiz** [comment]
This : 

```
python __main__.py -i http://www.crunchyroll.com/kemono-friends/episode-8-ppp-live-728273 -u username -p password
```

**Comment by Haejien** [comment]
Alright that did it, worked successfully.

**Comment by Xonshiz** [comment]
NICE! Finally! And thank you so much for pointing this out and helping me fix this shiznit :)
