### ISSUE TITLE
ImportError: No module named anime_dl

### ISSUE THREAD

**Issue by gnouv** [Xonshiz/anime-dl#28]
hello,

i got error when trying to call script.

i did chmod, installed Dependencies, installed python 3.6, nodejs, ...

Thanks

```
Traceback (most recent call last):
  File "./__main__.py", line 9, in <module>
    from AnimeDL import *
  File "/root/anime_dl/anime-dl-master/anime_dl/AnimeDL.py", line 8, in <module>
    import sites
  File "/root/anime_dl/anime-dl-master/anime_dl/sites/__init__.py", line 1, in <module>
    import sites.crunchyroll
  File "/root/anime_dl/anime-dl-master/anime_dl/sites/crunchyroll.py", line 25, in <module>
    from anime_dl import animeName
ImportError: No module named anime_dl

```

**Comment by Xonshiz** [comment]
This will not work on Python 3.6. I'd suggest using Python 3.4 or lower.
