### ISSUE TITLE
Issues running in windows

### ISSUE THREAD

**Issue by flyingpengwin** [Xonshiz/anime-dl#30]
Hello, 
Thank you so much for taking the time to create this software. I have python, nodejs, RTMPDump, and mkvmerge.exe installed and in my %PATH%. I have downloaded the anime-dl-master.zip and unpacked it and did the pip install. I have downloaded the anime-dl.exe binary and placed it into the anime-dl-master folder as well as in the anime_dl folder. No matter what I do I still get the same error. If I run it as the binary
 `anime-dl.exe -i https://www.funimation.com/shows/my-hero-academia/ -u PRIVATE -p PRIVATE -v -l dub`
I get an output like:
('This lang : ', 'dub')
Traceback (most recent call last):
  File "anime_dl\__main__.py", line 19, in <module>
  File "anime_dl\__main__.py", line 73, in main
  File "anime_dl\AnimeDL.py", line 45, in __init__
  File "anime_dl\sites\funimation.py", line 19, in __init__
  File "anime_dl\sites\funimation.py", line 74, in singleEpisode
AttributeError: 'NoneType' object has no attribute 'group'
[9428] Failed to execute script __main__

If I try to run it under the __main__.py inside the anime_dl folder I get:
Traceback (most recent call last):
  File "C:\PATH\anime-dl-master\anime_dl\__main__.py", line 9, in <module>
    from AnimeDL import *
  File "C:\PATH\anime-dl-master\anime_dl\AnimeDL.py", line 8, in <module>
    import sites
  File "C:\PATH\anime-dl-master\anime_dl\sites\__init__.py", line 1, in <module>
    import crunchyroll
ModuleNotFoundError: No module named 'crunchyroll'

Could you give me any advice?

Thanks

**Comment by Xonshiz** [comment]
Could you please make sure that the show you're tying to download is indeed available in your region? There are some shows that aren't available in some region. If that's the case, then script will not download those.
Also, there is a Error_log.log file that is written when you start the script in verbose mode. Please also attach that file here. Do remember to remove your credentials from that file before uploading anywhere.

**Comment by Xonshiz** [comment]
Just checked your URL. It's a wrong URL. It's throwing 404 (i.e., the page doesn't exist). Try opening that link in the browser. Plus, that series is not on crunchyroll.

**Comment by flyingpengwin** [comment]
Hello,
 I'm sorry it's taken so long for me to get back to you. (I'm new to github and didn't realize I could reply to a closed issue.) When I created the issue I changed the url and messed it up. I have edited the original post to reflect the valid url. The series is for funimation not crunchyroll which lead to more confusion. I am also adding the errorlog.log. And don't worry, I've removed my credentials. The first error is `C:\Path\anime-dl-master\anime-dl\anime-dl.exe -i https://www.funimation.com/shows/my-hero-academia/ -u PRIVATE -p PRIVATE -v -l dub` and the second one replaceing anime-dl.exe with __main__.py
[Error Log.log](https://github.com/Xonshiz/anime-dl/files/1613523/Error.Log.log)

Please let me know if there is anything else you need.

**Comment by Xonshiz** [comment]
Hey! Sorry, currently Funimation is not supported. They have changed their
internal working and I don't have all the necessary details regarding the
working of it. I'll most probably look into this after this month. I cannot
promise anything, sorry.
If you, or anyone knows about the process, please feel free to share.

**Comment by flyingpengwin** [comment]
O ok. I have a friend thats a backend website dev. I plan on asking him if he has any ideas, if I find something I'll share. Thanks for the quick responds!

**Comment by Xonshiz** [comment]
That'll be great!

**Comment by flyingpengwin** [comment]
I don't know how much it helps but it seems that the raw is encrypted now but you can get the link to the video by going through the source and finding "/player/519905/?bdub=0" for example would be https://www.funimation.com/player/519905/?bdub=0 for Black Clover 1 Eng

**Comment by Xonshiz** [comment]
Hey,

I've figured a little bit more than this. I was able to track their APIs
and get the things I need to some extent. I'll start working on this next
month and hopefully I'll be able to implement it soon.




Thank You,
Dhruv Kanojia
(Github <https://github.com/Xonshiz>| Website <http://psychoticelites.com/>
| Twitter <https://twitter.com/Xonshiz> | LinkedIn
<https://in.linkedin.com/in/dhruvkanojia> | Google+
<https://plus.google.com/+DhruvKanojia>)
