### ISSUE TITLE
Error parsing Cloudflare IUAM Javascript challenge. Cloudflare may have changed their technique, or there may be a bug in the script.

### ISSUE THREAD

**Issue by Abu3safeer** [Xonshiz/anime-dl#48]
![2018-04-08_22-41-37](https://user-images.githubusercontent.com/12091003/38471765-685aa968-3b7e-11e8-8d2f-2d8c8ceee8bc.png)

In text:
```
Trying to login...
Traceback (most recent call last):
  File "anime_dl\__main__.py", line 18, in <module>
  File "anime_dl\__main__.py", line 75, in main
  File "anime_dl\AnimeDL.py", line 30, in __init__
  File "anime_dl\sites\crunchyroll.py", line 46, in __init__
  File "anime_dl\sites\crunchyroll.py", line 82, in webpagedownloader
  File "requests\sessions.py", line 521, in get
  File "site-packages\cfscrape\__init__.py", line 47, in request
  File "site-packages\cfscrape\__init__.py", line 77, in solve_cf_challenge
  File "site-packages\cfscrape\__init__.py", line 107, in solve_challenge
ValueError: Error parsing Cloudflare IUAM Javascript challenge. Cloudflare may have changed their technique, or there may be a bug in the script.

Please read https://github.com/Anorov/cloudflare-scrape#updates, then file a bug report at https://github.com/Anorov/cloudflare-scrape/issues.
[6788] Failed to execute script __main__
```

**Comment by OgnistyPoland** [comment]
https://github.com/Xonshiz/anime-dl/releases/tag/2018.01.27.a

**Comment by Abu3safeer** [comment]
Sorry, didn't notice the update.
Thank you very much.
