### ISSUE TITLE
ValueError: Error parsing Cloudflare IUAM Javascript challenge

### ISSUE THREAD

**Issue by leptoid** [Xonshiz/anime-dl#49]
Looks like it is broken again.  I guess Cloudflare changed their scripts.
[Screen Output](https://gist.github.com/leptoid/e9228581658026a2ae07284197e6ba07)

```
c:\>anime-dl -u ploplord -p DukePlopsalots -r 480p -rn 9 -i http://www.crunchyroll.com/twin-star-exorcists
Trying to login...
Traceback (most recent call last):
  File "anime_dl\__main__.py", line 18, in <module>
  File "anime_dl\__main__.py", line 75, in main
  File "anime_dl\AnimeDL.py", line 30, in __init__
  File "anime_dl\sites\crunchyroll.py", line 54, in __init__
  File "anime_dl\sites\crunchyroll.py", line 82, in webpagedownloader
  File "requests\sessions.py", line 521, in get
  File "site-packages\cfscrape\__init__.py", line 47, in request
  File "site-packages\cfscrape\__init__.py", line 77, in solve_cf_challenge
  File "site-packages\cfscrape\__init__.py", line 107, in solve_challenge
ValueError: Error parsing Cloudflare IUAM Javascript challenge. Cloudflare may have changed their technique, or there may be a bug in the script.

Please read https://github.com/Anorov/cloudflare-scrape#updates, then file a bug report at https://github.com/Anorov/cloudflare-scrape/issues.
[9224] Failed to execute script __main__
c:\>
```

**Comment by leptoid** [comment]
Oh, I should let you know, "ploplord" and "DukePlopsalots" are not my actual login credentials.  lol

**Comment by leptoid** [comment]
and... I found my issue.  I was testing using -rn for a single episode number instead of multiple 
```
eg.  -rn 9
vs
eg.  -rn 9-10
```

I knew the syntax and have used it properly lots of times, It just seemed to make sense that this could be done with a single digit as a possibility.  Programming does not work that way.  It is an exact science.

This could be marked as resolved or enhancement (to make it so you can just use range with episode number).
