### ISSUE TITLE
Downloading from Funimation dont work 

### ISSUE THREAD

**Issue by danielkp1234** [Xonshiz/anime-dl#52]
so trying to download from funimation with anime-dl.exe -i "https://www.funimation.com/shows/fairy-tail/" -u "PRIVATE" -p "PRIVATE" -r "1080p" -l "english" -rn 1-10 but get this error 
('This lang : ', 'english')
Traceback (most recent call last):
  File "anime_dl\__main__.py", line 18, in <module>
  File "anime_dl\__main__.py", line 75, in main
  File "anime_dl\AnimeDL.py", line 46, in __init__
  File "anime_dl\sites\funimation.py", line 16, in __init__
  File "anime_dl\sites\funimation.py", line 71, in singleEpisode
AttributeError: 'NoneType' object has no attribute 'group'
[6900] Failed to execute script __main__

attached my error log file changed my password and username to PRIVATE in log and command
[Error Log.log](https://github.com/Xonshiz/anime-dl/files/1951772/Error.Log.log)

**Comment by Xonshiz** [comment]
Check #30

**Comment by danielkp1234** [comment]
Do you have an update on it if its soon and have you not said that it would work eith subs ?

**Comment by Xonshiz** [comment]
No update. As soon as I get some time and motivation, I'll work on it.

**Comment by Oujiii** [comment]
Hey, is it still not working? Just asking before trying in order to not be frustrated.
Thank you for your hard work!
