### ISSUE TITLE
Feature Request: Update "range" argument to allow pick latest # of episodes

### ISSUE THREAD

**Issue by axipher** [Xonshiz/anime-dl#62]
It would be nice to use the range argument to also only grab the latest # of episodes as well by entering just a negative number or some other form of argument followed by a number.

**Comment by Xonshiz** [comment]
Will consider this :)

**Comment by axipher** [comment]
Would it be possible to even just update the current method to allow putting 9999 as the upper range and in the program, check the range lower and upper values against the actual episode count.

So let's say a show I am watching has 117 episode currently on Crunchyroll, and the current season starts at 106.

If I add the "-rn 106-117" there is no problem, but if I do "-rn 106-118" or "-rn 106-9999" and the program throws an error:

`Trying to login...
Logged in successfully...
Traceback (most recent call last):
  File "anime_dl\__main__.py", line 18, in <module>
  File "anime_dl\__main__.py", line 75, in main
  File "anime_dl\AnimeDL.py", line 30, in __init__
  File "anime_dl\sites\crunchyroll.py", line 57, in __init__
  File "anime_dl\sites\crunchyroll.py", line 400, in wholeShow
IndexError: list index out of range
[13396] Failed to execute script __main__`

Then simply update the upper range to match the number of episodes in the show so that the same command can be used week after week to get the latest episodes of just the current season.



Right now I need to keep 100GB of the first seasons worth of episodes in the Output folder so that it skips them; or each week update the command with a new upper range value.
