### ISSUE TITLE
windows: cannot login to crunchyroll

### ISSUE THREAD

**Issue by dsolisp** [Xonshiz/anime-dl#66]
> Trying to login...
> Unable to Log you in. Check credentials again.
> Traceback (most recent call last):
>   File "anime_dl\__main__.py", line 18, in <module>
>   File "anime_dl\__main__.py", line 75, in main
>   File "anime_dl\AnimeDL.py", line 30, in __init__
>   File "anime_dl\sites\crunchyroll.py", line 47, in __init__
> TypeError: 'NoneType' object is not iterable
> [9728] Failed to execute script __main__

worked before with no problems, I have not made changes to my system

**Comment by Thedarklife74** [comment]
same problem

**Comment by Thedarklife74** [comment]
I think its because of the new player ...

**Comment by Thedarklife74** [comment]
Ok I found I semi-automatised solution by myself

**Comment by axipher** [comment]
Also having the same problem, same error and line numbers.

> 
> 
> Ok I found I semi-automatised solution by myself

What was your solution, can you please share

**Comment by Thedarklife74** [comment]
> Also having the same problem, same error and line numbers.
> 
> > Ok I found I semi-automatised solution by myself
> 
> What was your solution, can you please share

So. For the video you need to use an extension like flash video downloader or download helper to get the video link of the m3u8. With the link m3u8 use ffmpeg to get it in mp4. For the subtitle when you play the video on the website use the insepctor tool of your browser and apply a filter to show txt file who are loaded. On of the 3 are the subtitle open it in a new tab and save the page as an .ass.  Then you just need to rename your .mp4 in .mkv and merge with the subtitle. I already send this solution to the creator of this project to helping him to update but no reponse yet so ...

**Comment by axipher** [comment]
Okay, I'll have to figure that out later, thank though.  I checked in Firefox and it doesn't seem to have a way to see the downloaded subtitles file that I can tell.

**Comment by Thedarklife74** [comment]
> I just checked and the Crunchyroll-Downloader by skid9000 that uses his CrunchyrollAuth code seems to work perfectly fine still. So not sure if it might be an option to switch to that Login code or not. I'm still pretty green in Python so I don't feel comfortable mucking around the code.

OK thanks but I'm looking for a Windows solution so...

**Comment by Barbait** [comment]
same problem for me

**Comment by leptoid** [comment]
> 
> 
> I just checked and the Crunchyroll-Downloader by skid9000 that uses his CrunchyrollAuth code seems to work perfectly fine still. So not sure if it might be an option to switch to that Login code or not. I'm still pretty green in Python so I don't feel comfortable mucking around the code.

If only it did episode ranges and subcategorized videos into respective show folders.  Thus, I feel anime-dl is superior, you know... when the login isn't broken. :)

**Comment by axipher** [comment]
> 
> 
> > I just checked and the Crunchyroll-Downloader by skid9000 that uses his CrunchyrollAuth code seems to work perfectly fine still. So not sure if it might be an option to switch to that Login code or not. I'm still pretty green in Python so I don't feel comfortable mucking around the code.
> 
> If only it did episode ranges and subcategorized videos into respective show folders. Thus, I feel anime-dl is superior, you know... when the login isn't broken. :)

I tried to take a quick look through Xonshiz's code, I *think* he's using portions of the youtube-dl code instead of the actual youtube-dl executable itself.  I'm sure if I spent more time looking I might be able to figure out what's going on, but maybe the cookies.txt that gets generated by Crunchyroll-Auth (or by running  Crunchyroll-Downloader once and checking in ProgramData), we can pass that cookies.txt to anime-dl to bypass the login issue.

I do agree that I much prefer anime-dl as it seperates downloads by show name along with adding the resolution to the filenames.

**Comment by Xonshiz** [comment]
Adding onto the information you all have gathered, I think the issue is within the login page. Anime-dl checks "Redirecting...." in the title. At least it used to, because Crunchyroll had an intermediate page after successfull sign in. This is what I used to find whether the user has logged in or not. Apparently, they've changed this and removed that page. But, they've added some other page.

Unfortunately, I don't have a premium account now and my account has expired. So, I tried wit ha trial account and they DO have a new page in between. I'm not planning on getting a subscription anytime soon. I'll see what can be done.

About the player thing, they might've changed things, but the script works, so meh. Let it be. I have to change the complete script anyway. I'll look into that later.

For now, please have fun with this one.

**Comment by Thedarklife74** [comment]
Hi ! I juste test now but it seems it doesn't work (I have a premium account)

DEBUG: You have successfully set the Debugging On.
DEBUG: Arguments Provided : Namespace(input=['https://www.crunchyroll.com/that-time-i-got-reincarnated-as-a-slime/episode-2-meeting-the-goblins-777520'], language='Japanese', password=['xxxxxxx'], range='All', resolution=['720'], skip=False, username=['xxxxx'], verbose=True, version=False)
DEBUG: Operating System : Windows - 10 - 10.0.17763
DEBUG: Python Version : 2.7.14 (32bit)
DEBUG: Starting new HTTPS connection (1): www.crunchyroll.com
DEBUG: https://www.crunchyroll.com:443 "GET /login HTTP/1.1" 503 None
DEBUG: Resetting dropped connection: www.crunchyroll.com
DEBUG: https://www.crunchyroll.com:443 "GET /cdn-cgi/l/chk_jschl?jschl_answer=157.4918906686&jschl_vc=f5c1400b4e53cd8dd0d221a9b60cd133&pass=1539208221.237-J4Xe3VFJmn HTTP/1.1" 302 159
DEBUG: https://www.crunchyroll.com:443 "GET /login HTTP/1.1" 200 None
DEBUG: https://www.crunchyroll.com:443 "POST /login HTTP/1.1" 302 None
DEBUG: https://www.crunchyroll.com:443 "GET / HTTP/1.1" 200 None

**Comment by Thedarklife74** [comment]
My bad I will try with a clan install and test

**Comment by Thedarklife74** [comment]
Ok I just fogot to update the .exe now I can confirm It work well ;) Thanks a lot !
