### ISSUE TITLE
Cannot download with new version

### ISSUE THREAD

**Issue by MrDonGato** [Xonshiz/anime-dl#7]
Command Line Argument:  

anime-dl -i "http://www.crunchyroll.com/saekano-how-to-raise-a-boring-girlfriend-" -u "xxxxx" -p "xxxxxxxxx"
Trying to login...
Traceback (most recent call last):
  File "site-packages\cfscrape\__init__.py", line 109, in solve_challenge
  File "site-packages\execjs\_runtimes.py", line 22, in get
  File "site-packages\execjs\_runtimes.py", line 61, in _find_runtime_by_name
execjs._exceptions.RuntimeUnavailableError: Node.js (V8) runtime is not available on this system

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "anime_dl\__main__.py", line 16, in <module>
  File "anime_dl\__main__.py", line 56, in main
  File "anime_dl\AnimeDL.py", line 27, in __init__
  File "anime_dl\sites\crunchyroll.py", line 41, in __init__
  File "anime_dl\sites\crunchyroll.py", line 68, in webpagedownloader
  File "site-packages\requests\sessions.py", line 501, in get
  File "site-packages\cfscrape\__init__.py", line 47, in request
  File "site-packages\cfscrape\__init__.py", line 77, in solve_cf_challenge
  File "site-packages\cfscrape\__init__.py", line 111, in solve_challenge
OSError: Missing Node.js runtime. Node is required. Please read the cfscrape README's Dependencies section: https://github.com/Anorov/cloudflare-scrape#dependencies.
Failed to execute script __main__

Long Explanation : 

Tried the new version because i was waiting for the only subs version, but when i try to download anything, it shows me this error. I tried the old version and it worked well.

Please let me know if i'm doing anything wrong.

regards!

**Comment by Xonshiz** [comment]
Please re-read the "[Read Me](https://github.com/Xonshiz/anime-dl#dependencies-installation)", you now need `FFmpeg` and `Node.js` in your systems to be able to run this script. And it's also mentioned in the error you posted 

```
File "site-packages\execjs_runtimes.py", line 61, in _find_runtime_by_name
execjs._exceptions.RuntimeUnavailableError: Node.js (V8) runtime is not available on this system
```
