### ISSUE TITLE
Error downloading hunter X hunter

### ISSUE THREAD

**Issue by spoilalot** [Xonshiz/anime-dl#9]
anime-dl.exe -i "http://www.crunchyroll.com/hunter-x-hunter/episode-1-departure-x-and-x-friends-584886" -u "" -p "" -r "1080p"

Trying to login...
Logged in successfully...
Grabbing Links for 1080p Streams.
Writing subtitles to files...
Writing subtitles to files...
Writing subtitles to files...
Writing subtitles to files...
Traceback (most recent call last):
  File "anime_dl\__main__.py", line 16, in <module>
  File "anime_dl\__main__.py", line 56, in main
  File "anime_dl\AnimeDL.py", line 27, in __init__
  File "anime_dl\sites\crunchyroll.py", line 38, in __init__
  File "anime_dl\sites\crunchyroll.py", line 167, in singleEpisode
  File "site-packages\requests\sessions.py", line 501, in get
  File "site-packages\cfscrape\__init__.py", line 39, in request
  File "site-packages\requests\sessions.py", line 488, in request
  File "site-packages\requests\sessions.py", line 603, in send
  File "site-packages\requests\sessions.py", line 685, in get_adapter
requests.exceptions.InvalidSchema: No connection adapters were found for 'mp4:c6/s/ve762525/video.mp4'
Failed to execute script __main__

**Comment by Xonshiz** [comment]
Fixed. Please re-check the ReadMe's Dependencies section for more information on how to get around this issue.
